hwNhrAnrME hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwLhrOnrCATION/AFILS hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwShrHnrELL hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwhrnr hwLhrAnrST.SEEN hwhrnr hwhrnr hwOhrNnr hwhrnr hwhrnr hwhrnr hw[hrnnrprftdeh] hwhrnr hwhrnr hwUhrnr hwhrnr hwhrnr hwDhrnr hwhrnr hwhrnr hwPhrnr hwhrnr hwhrnr hwhrnr hwFhrInrRST hwhrnr hwhrnr hwhrnr hwhrnr hwChrOnrN
hrnolageek                  nrCapitol Shrill BBS             hrcapshril    hk02h 54m     nr61m   hk[-nr-------hk]  nrTelne
hrCJ                        nrOrange City, FL                hrcapshril    hk03d 08h     nr4m    hk[hgInnwnr--f-d--hk]  nrTelne
hrSmooth                    nrCovina, CA                     hrcapshril    hk07d 13h     nr3m    hk[-nr-r----hhk]  nrTelne
hrpaulie420                 nr2o fOr beeRS                   hrcapshril    hk11d 20h     nr6m    hk[-nrprf-d--hk]  nrTelne
hrlux                       nrLas Vegas NV.                  hramigaish    hk12d 15h     nr14m   hk[hgInnwnr-r--d-hhk]  nrTelne
hrGenny Lane                nrFrogmore, SC                   hrcapshril    hk12d 22h     nr29m   hk[hgInnwnr------hhk]  nrTelne
hrSynner                    nrsomewhere. someplace           hramigaish    hk17d 13h     nr21m   hk[hgInnwnr-rf-d--hk]  nrTelne
hrAlpha                     nrBerkeley, Ca                   hrcapshril    hk20d 01h     nr26m   hk[-nr-r--d--hk]  nrTelne
hrCrash                     nrConroe                         hrcapshril    hk20d 09h     nr14m   hk[hgInnwnr--f-d-hhk]  nrTelne
hrAnachronist               nrImp!^void^phenom               hramigaish    hk20d 14h     nr4m    hk[-nr------hhk]  nrTelne
hrCrewmate                  nrCrewmate's Test Lab            hrcapshril    hk20d 23h     nr0m    hk[hgInnwnr--f----hk]  nrTelne
hrZylone                    nrpLANET cARAVAN BBS             hrcapshril    hk22d 23h     nr3m    hk[-nr----d--hk]  nrTelne
hrTruly                     nrusa                            hrcapshril    hk27d 15h     nr11m   hk[hgInnwnr--f---hhk]  nrTelne
hrhollowone                 nroftenhide                      hrcapshril    hk30d 07h     nr30m   hk[-nr-r--d--hk]  nrTelne
hrHarry Caray               nrVA                             hrcapshril    hk32d 17h     nr5m    hk[-nr------hhk]  nrTelne
hrZos_Kia                   nrFrance                         hrcapshril    hk32d 21h     nr65m   hk[hgInnwnr-rf-d-hhk]  nrTelne
hrInfectedBootSector        nrSeverna Park, Maryland         hrcapshril    hk38d 14h     nr6m    hk[-nr-r--d-hhk]  nrTelne
hrno2pencil                 nrBaltimore, Md                  hrcapshril    hk60d 12h     nr11m   hk[-nr-rf-de-hk]  nrTelne
hrJdavid                    nrSciotoville, Ohio              hrcapshril    hk67d 12h     nr3m    hk[-nr-------hk]  nrTelne
hrMuldar                    nra house in GA                  hrcapshril    hk80d 20h     nr3m    hk[hgInnwnr-rf---hhk]  nrTelne
hrLimping Ninja             nrVaxholm, Sweden                hrcapshril    hk81d 23h     nr3m    hk[-nr-r----hhk]  nrTelne
hwnhrenrwuser hwphronrstmsg hwrhrenradmsg hwfhrenredback hwthrfnriles hwdhronrors hwehrmnrail hwhhranrngup hw/hrnr hwUhrpnrloaded hwDhronrwnloaded hwPhronrsted
